#+TITLE: Git Hooks Collection
#+AUTHOR: Roman Zayrullin
#+EMAIL: krosenmann@gmail.com
#+STARTUP: showall
#+LaTeX_ClASS_OPTIONS: [11pt,a4paper,ubuntu]
#+LaTeX_HEADER:\usepackage[scale=0.75]{geometry}
#+LaTeX_HEADER:\usepackage[utf-8]{inputrec}

Хуки, облегчающие трудовыебудни.
* Проверка на брейкпоинты и временный код.
  Помечать временный код -- хорошее решение. Помечайте временный
  код. Называйте специфично временные переменные, или добавляйте
  соответствующий комментарий. Я, например, для помечания временного кода
  использую слово ~Petuch~ в данных, комментариях или как имя
  временной переменной, используемой для отладки.
  При использовании бряков у гнутого семейства дебаггеров, есть
  необходимость проверять его наличие в коде перед коммитом. 
  Хук отлавливает помеченный временный код и бряки гнутых дебаггеров и
  прерывает коммит при их нахождении. 
#+NAME: Проверка на наличие нежелательного\временного кода
#+BEGIN_SRC shell :export results
pdb_check=$(git grep -i '; Tracer()()\|.set_trace()\|petuch' -- '*.py')

if [ ${#pdb_check} -gt 0 ]
then
        echo -e "\e[31mCOMMIT REJECTED: commit contains code with break points. Please remove before commiting.\e[0m"
        echo $pdb_check
        exit 1
else
        echo -e "\e[36mCode contains no break points\e[0m"
fi
#+end_src

#+RESULTS: Проверка на наличие нежелательного\временного кода
: [36mCode contains no break points[0m

Тестирование джанго-проектов
#+NAME: commit_after_tests
#+begin_src shell
source .venv/bin/activate
./manage.py test
RESULT=$?
if [ $RESULT -ne 0 ]
then
    echo -e "\e[31mCOMMIT REJECTED: Test's failed!\e[0m"
    exit 1
else
    echo -e "\e[36mTest Passed\e[0m"
fi

exit 0
#+end_src
* Интерактивная сборка
  В блок кода ниже вставить имена чанков в noweb-синтаксисе и
  выполнить ~org-babel-tanle~ (по-умолчанию ~C-c C-v t~)
  #+BEGIN_SRC shell :tanle pre-commit
    <<check_bps>>
  #+END_SRC
