#+TITLE: Git Hooks Collection
#+AUTHOR: Roman Zayrullin
#+EMAIL: krosenmann@gmail.com
#+EXPORT_FILE_NAME: README
#+STARTUP: showall
#+LaTeX_ClASS_OPTIONS: [11pt,a4paper,ubuntu]
#+LaTeX_HEADER:\usepackage[scale=0.75]{geometry}
#+LaTeX_HEADER:\usepackage[utf-8]{inputrec}

Хуки, облегчающие трудовыебудни.
#+name: l10n
#+begin_src shell :export no
  GETTEXT='gettext "kr-githooks"'
#+end_src

#+RESULTS: l10n

* Проверка на брейкпоинты и временный код.
  Помечать временный код -- хорошее решение. Помечайте временный
  код. Называйте специфично временные переменные, или добавляйте
  соответствующий комментарий. Я, например, для помечания временного кода
  использую слово ~Petuch~ в данных, комментариях или как имя
  временной переменной, используемой для отладки.
  Хук отлавливает помеченный временный код, забытые бряки гнутых
  дебаггеров и прерывает коммит при их нахождении.
#+NAME: Проверка на наличие нежелательного\временного кода
#+HEADER: :var REGXP_TC="; Tracer()()\\|.set_trace()\\|petuch" :var F_MASK="*.py"
#+BEGIN_SRC shell :noweb no-export
  REJECT_MESSAGE=$($GETTEXT "COMMIT REJECTED: commit contains code with break points. Please remove before commiting.")
  CLEAR_STATUS_MESSAGE=$($GETTEXT "Code contains no break points")
  tc_check=$(git grep -i "$REGXP_TC" -- "$F_MASK")
  if [ ${#tc_check} -gt 0 ]
  then
          echo -e $tc_check "\e[31m$REJECT_MESSAGE\e[0m" | cowsay -f dragon
          exit 1
  else
          echo -e $tc_check "\e[36m$CLEAR_STATUS_MESSAGE\e[0m" | cowsay
  fi
#+end_src

#+RESULTS: Проверка на наличие нежелательного\временного кода
: [36mCode contains no break points[0m

* Контроль тестирования\сборки
Перед коммитов выполняется команда на контроль качества. Прогон
тестов, сборка.

#+NAME: тесты перед коммитом
#+header: :var QCONTROL_COMMAND="./manage.py test"
#+begin_src shell :noweb no-export 
  TEST_PASSED=$($GETTEXT "\e[36mAll Test Passed\e[0m")
  TEST_FAILED=$($GETTEXT "\e[31mCOMMIT REJECTED: Test's failed!\e[0m")
  $QCONTROL_COMMAND
  RESULT=$?
  if [ $RESULT -ne 0 ]
  then
      echo -e $TEST_FAILED | cowsay -f dragon
      exit 1
  else
      echo -e $TEST_PASSED | cowsay 
  fi
#+end_src

#+RESULTS: тесты перед коммитом

** Интерактивная сборка
  
   В блок кода ниже вставить имена чанков в noweb-синтаксисе и
   выполнить ~org-babel-tangle~ (по-умолчанию ~C-c C-v t~)
   #+NAME: precommit-django-exmpl
   #+BEGIN_SRC shell :tangle pre-commit :noweb no-export
     #!/bin/bash
     {{{l10n}}}
     REGXP_TC="; Tracer()()\|.set_trace()\|petuch"
     F_MASK="*.py"
     QCONTROL_COMMAND="./manage.py test"
     {{{Проверка на наличие нежелательного\временного кода}}}
     {{{тесты перед коммитом}}}
     exit 0
   #+END_SRC

   #+RESULTS: precommit-django-exmpl

* Вставка имени ветки в сообщение коммита
  Всякие ЖИРО-образные системы любят, чтобы в сообщении коммита
  писались имена задач, чтобы их можно было вставлять в историю
  задач. И чтобы еще и ветки так же назывались. 
  По жиротрадиции, это что-то вроде FOO-1337.
  #+name: Имя ветки в начале сообщения коммита
  #+begin_src shell :noweb no-export :tangle prepare-commit-msg
    #!/bin/bash 
    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | grep "[[:upper:]].*-[[:digit:]].*")
    echo "$BRANCH_NAME" >> $1
  #+end_src

  #+RESULTS: Имя ветки в начале сообщения коммита

* Настройка и добавление хуков в репы
   При работе с литературным исходником можно выполнить настройку и
   сборку непосредственно из самого Emacs. Подробнее -- в литературном
   исходнике. 
** Бонус для емаксеров                                             :noexport:
   * Настройка
     1. Задать значения для переменных
     2. Вставить чанки интересующих хуков ~{{{<имя чанка>}}}~
     3. Выполнить ~C-c C-v t~
   * Установка
     1. Перейти в чанк "установка"
     2. В хедере чанка, в переменной PROJECT, задать путь до проекта
     3. В чанке "установка" выполнить ~C-c C-c~

   #+NAME: установка
   #+BEGIN_SRC shell :tangle no :var PROJECT="" :export no
     REPO=$PROJECT/.git/hooks/
     chmod +x pre-commit 
     chmod +x prepare-commit-msg
     cp pre-commit -t $REPO
     cp prepare-commit-msg $REPO
   #+END_SRC

   #+RESULTS:

* File-local variables                                             :noexport:  
  # Local Variables:
  # org-babel-noweb-wrap-start: "{{{"
  # org-babel-noweb-wrap-end: "}}}"
  # org-confirm-babel-evaluate: nil
  # org-export-allow-bind-keywords: t
  # End:
