#+TITLE: Git Hooks Collection
#+AUTHOR: Roman Zayrullin
#+EMAIL: krosenmann@gmail.com
#+EXPORT_FILE_NAME: README
#+STARTUP: showall latexpreview
#+LaTeX_ClASS_OPTIONS: [11pt,a4paper,ubuntu]
#+LaTeX_HEADER:\usepackage[scale=0.75]{geometry}
#+LaTeX_HEADER:\usepackage[utf-8]{inputrec}

Шаблоны git-хуков, облегчающие трудовыебудни.

#+name: l10n
#+begin_src shell :exports none
  GETTEXT='gettext "kr-githooks"'
#+end_src

#+RESULTS: l10n
И немного поднимающие настроение. Чтобы завести своего гитотамагочи,
установите ~cowsay~ и наслаждайтесь. А нет, так выпилите. Это ж
шаблон, в конце концов.
#+name: не разрешено
#+BEGIN_SRC shell :var cmd="TEST" :exports none :tangle no :results code
  echo "\"\e[31m$cmd\e[0m\" | cowsay -f bounty"
#+END_SRC

#+name: разрешено
#+BEGIN_SRC shell :var cmd="TEST" :exports none :tangle no :results code
echo "\"\e[36m$cmd\e[0m\" | cowsay"
#+END_SRC

* Проверка на брейкпоинты и временный код.
  Помечать временный код -- хорошее решение. Помечайте временный
  код. Называйте специфично временные переменные, или добавляйте
  соответствующий комментарий. Я, например, для помечания временного кода
  использую слово ~Petuch~ в данных, комментариях или как имя
  временной переменной, используемой для отладки.
  Хук отлавливает помеченный временный код, забытые бряки гнутых
  дебаггеров и прерывает коммит при их нахождении.

#+NAME: Проверка на наличие нежелательного\временного кода
#+HEADER: :var REGXP_TC="; Tracer()()\\|.set_trace()\\|petuch" :var F_MASK="*.py"
#+BEGIN_SRC shell :noweb yes
  REJECT_MESSAGE=$($GETTEXT "Кажется, тут сломанная ветка! Код содержит брейкпоинты или помеченные временные конструкции. Удалите их перед коммитом!")
  CLEAR_STATUS_MESSAGE=$($GETTEXT "Код не содержит бряков и временного кода")
  tc_check=$(git grep -i "$REGXP_TC" -- "$F_MASK")
  if [ ${#tc_check} -gt 0 ]
  then
          echo -e $tc_check {{{не разрешено("$REJECT_MESSAGE")}}}
          exit 1
  else
          echo -e $tc_check {{{разрешено("$CLEAR_STATUS_MESSAGE")}}}
  fi
#+end_src

#+RESULTS: Проверка на наличие нежелательного\временного кода
: [36mCode contains no break points[0m

* Контроль тестирования\сборки
Для сохранения целостности, нужно использовать команды контроля
качества (прогон тестов, сборка, другое на выбор). Эти процессы могут
быть долгими, в таких случаях их можно прогонять перед каждым пушем. 
Кроме того, можно установить целый каскад таких проверок, запуская их
как перед коммитами, так и перед пушами.  

#+NAME: тесты
#+header: :var QCONTROL_COMMAND="./manage.py test"
#+begin_src shell :noweb no-export 
  TEST_PASSED=$($GETTEXT "\e[36mТесты пройдены успешно\e[0m")
  TEST_FAILED=$($GETTEXT "
  \e[31mCOMMIT REJECTED: Кажется, тут сломанная ветка! 
  Убедитесь, что программа работает корректно и повторите попытку.\e[0m
  Если подозреваете, что в поломке виноват кто-то другой, 
  воспльзуйтесь командой\n
  \t\e[1mgit bisect\e[0m
  ")
  $QCONTROL_COMMAND
  RESULT=$?
  if [ $RESULT -ne 0 ]
  then
      echo -e $TEST_FAILED | cowsay -f bounty
      exit 1
  else
      echo -e $TEST_PASSED | cowsay 
  fi
#+end_src


** Сборка
  
   В блок кода ниже вставить имена чанков в noweb-синтаксисе и
   выполнить ~org-babel-tangle~ (по-умолчанию ~C-c C-v t~)
   #+NAME: precommit-django-exmpl
   #+BEGIN_SRC shell :tangle pre-commit :noweb no-export
     #!/bin/bash
     {{{l10n}}}
     REGXP_TC="; Tracer()()\|.set_trace()\|petuch"
     F_MASK="*.py"
     QCONTROL_COMMAND="./manage.py test"
     {{{Проверка на наличие нежелательного\временного кода}}}
     exit 0
   #+END_SRC

   #+NAME: prepush-django-exmpl
   #+BEGIN_SRC shell :tangle pre-push :noweb no-export :shebang #!/bin/bash
     {{{l10n}}}
     commands=("./manage.py test" "docker build --rm -t autocreated-by-git -f Dockerfile . ")
     for QCONTROL_COMMAND in "${commands[@]}"
     do
         {{{тесты}}}
     done
     # Очистка контейнера (кандидат на пост-пуш хук)
     docker rmi autocreated-by-git
   #+END_SRC

* Вставка имени ветки в сообщение коммита
  Всякие ЖИРО-образные системы любят, чтобы в сообщении коммита
  писались имена задач, чтобы их можно было вставлять в историю
  задач. И чтобы еще и ветки так же назывались. 
  По жиротрадиции, это что-то вроде FOO-1337.
  #+name: Имя ветки в начале сообщения коммита
  #+begin_src shell :noweb no-export :tangle prepare-commit-msg
    #!/bin/bash 
    NAME=$(git rev-parse --abbrev-ref HEAD | grep "[[:upper:]].*-[[:digit:]].*")

    DESCRIPTION=$(git config branch."$NAME".description)

    echo "$NAME"': '$(cat "$1") > "$1"
    if [ -n "$DESCRIPTION" ] 
    then
       echo "" >> "$1"
       echo $DESCRIPTION >> "$1"
    fi
  #+end_src

  #+RESULTS: Имя ветки в начале сообщения коммита

* Настройка и добавление хуков в репы
  
  Один из вариантов -- проекто-специфичные вещи описать в отдельном
  орг-файле. Для того, чтобы чанки из этого сурца были доступны для
  извлечения в проектном орг-файле, выполните ~M-x
  org-babel-lob-ingest~ и укажите путь до файла program.org

  В случае использования таблицы для описания значений переменных,
  нужно проследить в каком виде строки попадают в bash. 
  Иначе воспользуйтесь старым добрым src_bash{VAR='banana'} в хедере
  блока исходника.
  
   #+BEGIN_SRC org :tangle example.org :exports code
     ,#+TITLE: Пример настройки проекта
     ,#+AUTHOR: Roman Zayrullin
     ,#+EMAIL: krosenmann@gmail.com
     ,#+STARTUP: showall


     ,* На стройку!
     Проект настраивается заполнением таблицы. Каждая переменная необходима
     либо для работы и установки, а так же служит напоминанием, какой набор
     хуков в какой проект установлен. 
     ,#+TBLNAME: setup
     | Имя параметра    | значение                                    | Описание                                                   |
     |------------------+---------------------------------------------+------------------------------------------------------------|
     | REGXP_TC         | '; Tracer()()'                              | Регулярка с нежелательными последовательностями            |
     | F_MASK           | '*.py'                                      | Маска файлов, по которым ведется поиск последовательностей |
     | QCONTROL_COMMAND | './manage.py test'                          | Контрольная команда (тесты, сборка, етс.)                  |
     | PROJECT          | "/home/roman/sources/django-business-logic" | Путь до проекта                                            |
     |------------------+---------------------------------------------+------------------------------------------------------------|

     ,#+NAME: create-precommit
     ,#+header: :shebang #!/bin/bash :var F_MASK=setup[3, 1] :var QCONTROL_COMMAND=setup[4, 1] :var REGEXP_TC=setup[2, 1]
     ,#+BEGIN_SRC shell :noweb yes :tangle pre-commit :exports none :results output
       {{{l10n}}}
       {{{Проверка на наличие нежелательного\временного кода}}}
       {{{тесты перед коммитом}}}
     ,#+END_SRC

     ,#+RESULTS: create-precommit

     После того, как все необходимые параметры заданы:
     1. ~C-c C-v t~ - для извлечения чанков с хуками
     2. ~C-c C-c~ на строке CALL ниже

     ,#+CALL: установка(PROJECT=setup[5, 1])

     ,#+RESULTS:

     ,* File-local variables                                             :noexport:  
       # Local Variables:
       # org-babel-noweb-wrap-start: "{{{"
       # org-babel-noweb-wrap-end: "}}}"
       # org-confirm-babel-evaluate: nil
       # org-export-allow-bind-keywords: t
       # End:
   #+END_SRC
** Бонус для емаксеров
   * Настройка
     1. Задать значения для переменных
     2. Вставить чанки интересующих хуков ~{{{<имя чанка>}}}~
     3. Выполнить ~C-c C-v t~
   * Установка
     1. Перейти в чанк "установка"
     2. В хедере чанка, в переменной PROJECT, задать путь до проекта
     3. В чанке "установка" выполнить ~C-c C-c~

   #+NAME: установка
   #+BEGIN_SRC shell :tangle no :var PROJECT="/home/zayrullin/PycharmProjects/pollyCRM" :exports none
     REPO=$PROJECT/.git/hooks/
     chmod +x pre-commit 
     chmod +x pre-push
     chmod +x prepare-commit-msg
     mv pre-commit $REPO
     mv prepare-commit-msg $REPO
     mv pre-push $REPO
   #+END_SRC

   #+RESULTS: установка

* Дополнение
  А если станет совсем печально и скучно, то на фейлы можно поставить
  вот этого парня. Для установки извлеченный cow-файл поместите в
  =/usr/share/cowsay/cows=

  #+name: gondar say
  #+BEGIN_SRC artist :exports none :tangle bounty.cow
    ## Gondar
    ## krosenmann
    ## 2017
    $the_cow =  <<"EOC";                           
                                                  $thoughts
                                                   $thoughts
                                                    $thoughts      
                                                     $thoughts
                                                      $thoughts
                                                       $thoughts        
                                                        $thoughts  | \\
                                                 ,,        |: \\    / 
                             /""-.               + \\,     _|,: +- /|        
                       _ /"''     \\.,             \\  \\, _/   \\:| \\ |          
                    ./               \\    ,________\\   X-     \\|   \\             
                   / _,-'"\\           \\,-/          \\_/    \\      / \\-,            
                  |/'      \\     ,---/    \\           |  "{C\\    /C)|  \\         /\\
                          /   /""         |            \\__    ( \\ __/   ',      /  ",
                          | /"       .-.   \\            \\ \\-___''/  |,    ',   / ,"' 
                          /"      ,-'   \\, |             \\          | '-,   \\ /  ', 
                         /      .'        '-\\             \\         \\    \\   ',   ,'
                       /-     /'            |              ""\\       |    \\   | ,"
                      /     /'             ,-\\.               |"\\    ,    / ,. ', 
                   /'/    .'            ,-/    \\--------,__    \\  ""-"    \\/ /  : 
                 /' /      ',      ,---/       /-------,   '--'"\\         / /"-'  
               /'  /         ;    '.      ,-' /'        '"'-.---'\\       (__)    
             /'   /    ,--,__/      \\-, /'   /                    \\.             
           /'    | /  / /""  \\        .'   /'                       \\            
          |      /\\/__/|     |       /    /            /\\            \\ 
           -____/       -.__/        -----\\,__________/  \\___________/    
    EOC
  #+END_SRC
  
  #+NAME: test gondar
  #+BEGIN_SRC shell :exports results :results code 
    cowsay -f bounty "Кажется, здесь сломанная ветка"
  #+END_SRC

  #+RESULTS: test gondar
  #+BEGIN_SRC shell
   ________________________________
  < Кажется, здесь сломанная ветка >
   --------------------------------
                                                \
                                                 \
                                                  \      
                                                   \
                                                    \
                                                     \        
                                                      \  | \
                                               ,,        |: \    / 
                           /""-.               + \,     _|,: +- /|        
                     _ /"''     \.,             \  \, _/   \:| \ |          
                  ./               \    ,________\   X-     \|   \             
                 / _,-'"\           \,-/          \_/    \      / \-,            
                |/'      \     ,---/    \           |  "{C\    /C)|  \         /\
                        /   /""         |            \__    ( \ __/   ',      /  ",
                        | /"       .-.   \            \ \-___''/  |,    ',   / ,"' 
                        /"      ,-'   \, |             \          | '-,   \ /  ', 
                       /      .'        '-\             \         \    \   ',   ,'
                     /-     /'            |              ""\       |    \   | ,"
                    /     /'             ,-\.               |"\    ,    / ,. ', 
                 /'/    .'            ,-/    \--------,__    \  ""-"    \/ /  : 
               /' /      ',      ,---/       /-------,   '--'"\         / /"-'  
             /'  /         ;    '.      ,-' /'        '"'-.---'\       (__)    
           /'   /    ,--,__/      \-, /'   /                    \.             
         /'    | /  / /""  \        .'   /'                       \            
        |      /\/__/|     |       /    /            /\            \ 
         -____/       -.__/        -----\,__________/  \___________/    
  #+END_SRC

* File-local variables                                             :noexport:  
  # Local Variables:
  # org-babel-noweb-wrap-start: "{{{"
  # org-babel-noweb-wrap-end: "}}}"
  # org-confirm-babel-evaluate: nil
  # org-export-allow-bind-keywords: t
  # End:
