#+TITLE: Git Hooks Collection
#+AUTHOR: Roman Zayrullin
#+EMAIL: krosenmann@gmail.com
#+EXPORT_FILE_NAME: README
#+STARTUP: showall
#+LaTeX_ClASS_OPTIONS: [11pt,a4paper,ubuntu]
#+LaTeX_HEADER:\usepackage[scale=0.75]{geometry}
#+LaTeX_HEADER:\usepackage[utf-8]{inputrec}

Шаблоны git-хуков, облегчающие трудовыебудни.

#+name: l10n
#+begin_src shell :exports none
  GETTEXT='gettext "kr-githooks"'
#+end_src

#+RESULTS: l10n
И немного поднимающие настроение. Чтобы завести своего гитотамагочи,
установите ~cowsay~ и наслаждайтесь. А нет, так выпилите. Это ж
шаблон, в конце концов.
#+name: не разрешено
#+BEGIN_SRC shell :var cmd="TEST" :exports none :tangle no :results code
  echo "\"\e[31m$cmd\e[0m\" | cowsay -f dragon"
#+END_SRC

#+name: разрешено
#+BEGIN_SRC shell :var cmd="TEST" :exports none :tangle no :results code
echo "\"\e[36m$cmd\e[0m\" | cowsay"
#+END_SRC

* Проверка на брейкпоинты и временный код.
  Помечать временный код -- хорошее решение. Помечайте временный
  код. Называйте специфично временные переменные, или добавляйте
  соответствующий комментарий. Я, например, для помечания временного кода
  использую слово ~Petuch~ в данных, комментариях или как имя
  временной переменной, используемой для отладки.
  Хук отлавливает помеченный временный код, забытые бряки гнутых
  дебаггеров и прерывает коммит при их нахождении.

#+NAME: Проверка на наличие нежелательного\временного кода
#+HEADER: :var REGXP_TC="; Tracer()()\\|.set_trace()\\|petuch" :var F_MASK="*.py"
#+BEGIN_SRC shell :noweb yes
  REJECT_MESSAGE=$($GETTEXT "COMMIT REJECTED: Код содержит брейкпоинты или помеченные временные конструкции. Удалите их перед коммитом!")
  CLEAR_STATUS_MESSAGE=$($GETTEXT "Код не содержит бряков и временного кода")
  tc_check=$(git grep -i "$REGXP_TC" -- "$F_MASK")
  if [ ${#tc_check} -gt 0 ]
  then
          echo -e $tc_check {{{не разрешено("$REJECT_MESSAGE")}}}
          exit 1
  else
          echo -e $tc_check {{{разрешено("$CLEAR_STATUS_MESSAGE")}}}
  fi
#+end_src

#+RESULTS: Проверка на наличие нежелательного\временного кода
: [36mCode contains no break points[0m

* Контроль тестирования\сборки
Перед коммитов выполняется команда на контроль качества. Прогон
тестов, сборка.

#+NAME: тесты перед коммитом
#+header: :var QCONTROL_COMMAND="./manage.py test"
#+begin_src shell :noweb no-export 
  TEST_PASSED=$($GETTEXT "\e[36mТесты пройдены успешно\e[0m")
  TEST_FAILED=$($GETTEXT "
  \e[31mCOMMIT REJECTED: Тесты сломаны! 
  Убедитесь, что программа работает корректно и повторите попытку.\e[0m
  Если подозреваете, что в поломке виноват кто-то другой (или молодой вы), 
  воспльзуйтесь командой\n
  \tgit bisect
  ")
  $QCONTROL_COMMAND
  RESULT=$?
  if [ $RESULT -ne 0 ]
  then
      echo -e $TEST_FAILED | cowsay -f dragon
      exit 1
  else
      echo -e $TEST_PASSED | cowsay 
  fi
#+end_src

#+RESULTS: тесты перед коммитом

** Сборка
  
   В блок кода ниже вставить имена чанков в noweb-синтаксисе и
   выполнить ~org-babel-tangle~ (по-умолчанию ~C-c C-v t~)
   #+NAME: precommit-django-exmpl
   #+BEGIN_SRC shell :tangle pre-commit :noweb no-export
     #!/bin/bash
     {{{l10n}}}
     REGXP_TC="; Tracer()()\|.set_trace()\|petuch"
     F_MASK="*.py"
     QCONTROL_COMMAND="./manage.py test"
     {{{Проверка на наличие нежелательного\временного кода}}}
     {{{тесты перед коммитом}}}
     exit 0
   #+END_SRC

   #+RESULTS: precommit-django-exmpl

* Вставка имени ветки в сообщение коммита
  Всякие ЖИРО-образные системы любят, чтобы в сообщении коммита
  писались имена задач, чтобы их можно было вставлять в историю
  задач. И чтобы еще и ветки так же назывались. 
  По жиротрадиции, это что-то вроде FOO-1337.
  #+name: Имя ветки в начале сообщения коммита
  #+begin_src shell :noweb no-export :tangle prepare-commit-msg
    #!/bin/bash 
    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | grep "[[:upper:]].*-[[:digit:]].*")
    echo "$BRANCH_NAME" >> $1
  #+end_src

  #+RESULTS: Имя ветки в начале сообщения коммита

* Настройка и добавление хуков в репы
   При работе с литературным исходником можно выполнить настройку и
   сборку непосредственно из самого Emacs. Подробнее -- в литературном
   исходнике. 

** TODO Понять, а можно ли этот файл использовать, как подключаемый.
   Тогда сетап для хуков можно будет хранить в отдельном орг-файле, и
   этот полиморфный уебок не будет себя вести, как школьница. 
   Сетап в таблице, выполнение из кастомных файлов. Красота!
   А хули мне, собственно, стоит?
   #+BEGIN_SRC org :tangle example.org :exports code
     ,#+TITLE: Пример гит-хуков для проектов
     ,#+AUTHOR: Roman Zayrullin
     ,#+EMAIL: krosenmann@gmail.com
     ,#+STARTUP: showall
     ,#+INCLUDE: "./programm.org"

     ,* На стройку!
     ,#+tblname: awesome_django_setup
     | Имя параметра    | значение                                       |
     |------------------+------------------------------------------------|
     | REGXP_TC         | "; Tracer()()\\vert.set_trace()\\vert\ petuch" |
     | F_MASK           | "*.py"                                         |
     | QCONTROL_COMMAND | "./manage.py test"                             |
     | PROJECT          | "/home/roman/sources/learning-some-shit/"      |
     |------------------+------------------------------------------------|

     Возможное решение -- повернуть таблицу так, чтобы на одной строке
     находились параметры одного проекта, тогда можно будет применить
     табличную функцию, которая совершит весь нехитрый сетап!

     ,#+begin_src python :var keys=awesome_django_setup :results output table :colnames no
     print(keys)
     ,#+end_src

     ,#+RESULTS:
     | Имя параметра    | значение                                 |
     | REGXP_TC         | ; Tracer()()\vert.set_trace()\vertpetuch |
     | F_MASK           | *.py                                     |
     | QCONTROL_COMMAND | ./manage.py test                         |
     | PROJECT          | /home/roman/sources/learning-some-shit/  |
   #+END_SRC
** Бонус для емаксеров
   * Настройка
     1. Задать значения для переменных
     2. Вставить чанки интересующих хуков ~{{{<имя чанка>}}}~
     3. Выполнить ~C-c C-v t~
   * Установка
     1. Перейти в чанк "установка"
     2. В хедере чанка, в переменной PROJECT, задать путь до проекта
     3. В чанке "установка" выполнить ~C-c C-c~

   #+NAME: установка
   #+BEGIN_SRC shell :tangle no :var PROJECT="" :exports none
     REPO=$PROJECT/.git/hooks/
     chmod +x pre-commit 
     chmod +x prepare-commit-msg
     cp pre-commit -t $REPO
     cp prepare-commit-msg $REPO
   #+END_SRC

   #+RESULTS:
* Дополнение
  А если станет совсем печально и скучно, то на фейлы можно поставить
  вот этого парня с фразой "Кажется, тут сломанная ветка"
  #+name: gondar say
  #+BEGIN_SRC artist :exports none :tangle bounty.cow
    ## Gondar
    ## krosenmann
    ## 2017
    $the_cow =  <<"EOC";                           
                                                  $thoughts
                                                   $thoughts
                                                    $thoughts      
                                                     $thoughts
                                                      $thoughts
                                                       $thoughts        
                                                        $thoughts  | \\
                                                 ,,        |: \\    / 
                             /""-.               + \\,     _|,: +- /|        
                       _ /"''     \\.,             \\  \\, _/   \\:| \\ |          
                    ./               \\    ,________\\   X-     \\|   \\             
                   / _,-'"\\           \\,-/          \\_/    \\      / \\-,            
                  |/'      \\     ,---/    \\           |  "{C\\    /C)|  \\         /\\
                          /   /""         |            \\__    ( \\ __/   ',      /  ",
                          | /"       .-.   \\            \\ \\-___''/  |,    ',   / ,"' 
                          /"      ,-'   \\, |             \\          | '-,   \\ /  ', 
                         /      .'        '-\\             \\         \\    \\   ',   ,'
                       /-     /'            |              ""\\       |    \\   | ,"
                      /     /'             ,-\\.               |"\\    ,    / ,. ', 
                   /'/    .'            ,-/    \\--------,__    \\  ""-"    \\/ /  : 
                 /' /      ',      ,---/       /-------,   '--'"\\         / /"-'  
               /'  /         ;    '.      ,-' /'        '"'-.---'\\       (__)    
             /'   /    ,--,__/      \\-, /'   /                    \\.             
           /'    | /  / /""  \\        .'   /'                       \\            
          |      /\\/__/|     |       /    /            /\\            \\ 
           -____/       -.__/        -----\\,__________/  \\___________/    
    EOC
  #+END_SRC
  
  #+NAME: test gondar
  #+BEGIN_SRC shell :exports results :results code 
    cowsay -f bounty "Кажется, здесь сломанная ветка"
  #+END_SRC

  #+RESULTS: test gondar
  #+BEGIN_SRC shell
   ________________________________
  < Кажется, здесь сломанная ветка >
   --------------------------------
                                                \
                                                 \
                                                  \      
                                                   \
                                                    \
                                                     \        
                                                      \  | \
                                               ,,        |: \    / 
                           /""-.               + \,     _|,: +- /|        
                     _ /"''     \.,             \  \, _/   \:| \ |          
                  ./               \    ,________\   X-     \|   \             
                 / _,-'"\           \,-/          \_/    \      / \-,            
                |/'      \     ,---/    \           |  "{C\    /C)|  \         /\
                        /   /""         |            \__    ( \ __/   ',      /  ",
                        | /"       .-.   \            \ \-___''/  |,    ',   / ,"' 
                        /"      ,-'   \, |             \          | '-,   \ /  ', 
                       /      .'        '-\             \         \    \   ',   ,'
                     /-     /'            |              ""\       |    \   | ,"
                    /     /'             ,-\.               |"\    ,    / ,. ', 
                 /'/    .'            ,-/    \--------,__    \  ""-"    \/ /  : 
               /' /      ',      ,---/       /-------,   '--'"\         / /"-'  
             /'  /         ;    '.      ,-' /'        '"'-.---'\       (__)    
           /'   /    ,--,__/      \-, /'   /                    \.             
         /'    | /  / /""  \        .'   /'                       \            
        |      /\/__/|     |       /    /            /\            \ 
         -____/       -.__/        -----\,__________/  \___________/    
  #+END_SRC

* File-local variables                                             :noexport:  
  # Local Variables:
  # org-babel-noweb-wrap-start: "{{{"
  # org-babel-noweb-wrap-end: "}}}"
  # org-confirm-babel-evaluate: nil
  # org-export-allow-bind-keywords: t
  # End:
