#+TITLE: Git Hooks Collection
#+AUTHOR: Roman Zayrullin
#+EMAIL: krosenmann@gmail.com
#+STARTUP: showall
#+LaTeX_ClASS_OPTIONS: [11pt,a4paper,ubuntu]
#+LaTeX_HEADER:\usepackage[scale=0.75]{geometry}
#+LaTeX_HEADER:\usepackage[utf-8]{inputrec}

Хуки, облегчающие трудовыебудни.
#+name: l10n
#+begin_src shell
  GETTEXT='gettext "kr-githooks"'
#+end_src

#+RESULTS: l10n

* Проверка на брейкпоинты и временный код.
  Помечать временный код -- хорошее решение. Помечайте временный
  код. Называйте специфично временные переменные, или добавляйте
  соответствующий комментарий. Я, например, для помечания временного кода
  использую слово ~Petuch~ в данных, комментариях или как имя
  временной переменной, используемой для отладки.
  Хук отлавливает помеченный временный код, забытые бряки гнутых
  дебаггеров и прерывает коммит при их нахождении.
#+NAME: Проверка на наличие нежелательного\временного кода
#+HEADER: :var REGXP_TC="; Tracer()()\\|.set_trace()\\|petuch" :var F_MASK="*.py"
#+BEGIN_SRC shell :exports results :noweb no-export
  
  REJECT_MESSAGE=$($GETTEXT "COMMIT REJECTED: commit contains code with break points. Please remove before commiting.")
  CLEAR_STATUS_MESSAGE=$($GETTEXT "Code contains no break points")
  tc_check=$(git grep -i "$REGXP_TC" -- "$F_MASK")
  if [ ${#tc_check} -gt 0 ]
  then
          echo -e $tc_check "\e[31m$REJECT_MESSAGE\e[0m"
          exit 1
  else
          echo -e $tc_check "\e[36m$CLEAR_STATUS_MESSAGE\e[0m"
  fi
#+end_src

#+RESULTS: Проверка на наличие нежелательного\временного кода
: [36mCode contains no break points[0m

* Контроль тестирования\сборки
Перед коммитов выполняется команда на контроль качества. Прогон
тестов, сборка.

#+NAME: тесты перед коммитом
#+header: :var QCONTROL_COMMAND="./manage.py test"
#+begin_src shell :noweb no-export :exports no
  
  $QCONTROL_COMMAND
  TEST_PASSED=$($GETTEXT "\e[36mAll Test Passed\e[0m")
  TEST_FAILED=$($GETTEXT "\e[31mCOMMIT REJECTED: Test's failed!\e[0m")
  RESULT=$?
  if [ $RESULT -ne 0 ]
  then
      echo -e $TEST_FAILED
      exit 1
  else
      echo -e $TEST_PASSED
  fi
#+end_src

#+RESULTS: тесты перед коммитом

* Интерактивная сборка
  В блок кода ниже вставить имена чанков в noweb-синтаксисе и
  выполнить ~org-babel-tanle~ (по-умолчанию ~C-c C-v t~)
  #+NAME: django-exmpl
  #+BEGIN_SRC shell :tangle pre-commit :noweb yes
    #!/bin/bash
    {{{l10n}}}
    REGXP_TC="; Tracer()()\|.set_trace()\|petuch"
    F_MASK="*.py"
    QCONTROL_COMMAND="./manage.py test"
    {{{Проверка на наличие нежелательного\временного кода}}}
    {{{тесты перед коммитом}}}
  #+END_SRC

* Установка из emacs
  #+BEGIN_SRC shell :tangle no :var PROJECT="/home/roman/sources/goshabot"
    REPO=$PROJECT/.git/hooks/
    chmod +x pre-commit
    mv pre-commit $REPO
  #+END_SRC

  #+RESULTS:
  : /home/roman/sources/goshabot/.git/hooks/

* File-local variables                                             :noexport:  
  # Local Variables:
  # org-babel-noweb-wrap-start: "{{{"
  # org-babel-noweb-wrap-end: "}}}"
  # org-confirm-babel-evaluate: nil
  # org-export-allow-bind-keywords: t
  # End:
